# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppTransclustFile <- function(filename, threshold, use_custom_fallback = FALSE, sim_fallback = 0.0, p = 1.0, f_att = 100.0, f_rep = 100.0, R = 100L, dim = 3L, start_t = 100, d_init = 0.01, d_maximal = 5.0, s_init = 0.01, f_s = 0.01, fpt_time_limit = 20, fpt_max_cost = 5000, fpt_step_size = 10, disable_force = FALSE, disable_fpt = FALSE, file_type = "SIMPLE") {
    .Call('transclustr_cppTransclustFile', PACKAGE = 'transclustr', filename, threshold, use_custom_fallback, sim_fallback, p, f_att, f_rep, R, dim, start_t, d_init, d_maximal, s_init, f_s, fpt_time_limit, fpt_max_cost, fpt_step_size, disable_force, disable_fpt, file_type)
}

cppTransclustMatrix <- function(simmatrix, threshold, use_custom_fallback = FALSE, sim_fallback = 0.0, p = 1.0, f_att = 100.0, f_rep = 100.0, R = 100L, dim = 3L, start_t = 100, d_init = 0.01, d_maximal = 5.0, s_init = 0.01, f_s = 0.01, fpt_time_limit = 20, fpt_max_cost = 5000, fpt_step_size = 10, disable_force = FALSE, disable_fpt = FALSE) {
    .Call('transclustr_cppTransclustMatrix', PACKAGE = 'transclustr', simmatrix, threshold, use_custom_fallback, sim_fallback, p, f_att, f_rep, R, dim, start_t, d_init, d_maximal, s_init, f_s, fpt_time_limit, fpt_max_cost, fpt_step_size, disable_force, disable_fpt)
}

