// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// transclust
List transclust(NumericMatrix simmatrix);
RcppExport SEXP transclustr_transclust(SEXP simmatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type simmatrix(simmatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(transclust(simmatrix));
    return rcpp_result_gen;
END_RCPP
}
